# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45a4f96fdb80c22c47f2f8866ba5d41e7b87b0943ffdf99652db3461fea66064524a9102259bb59cc52920a57a21df87da11078474552b37881174d82da62034

test:
  secret_key_base: 63a211ed5c4d6d0afbff5bfd135d0d2d5d7b5c84c06a10dc569ea841fdc6aeae40c0c4d6a9301adbcc309a5e8162b08485852904e155f9b1e2e9faff5ea577e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
